Downgrade Protobuf to 3.29.3.0
This is necessary because Pro 3.6 references 3.29.9 and will be loaded
first in the process. In the debugger, no values are displayed due to
error CS1705 because that version is a release build/optimized without
symbols.